### PR TITLE
Migrating from dotnet6 to dotnet 8

### PR DESCRIPTION
**Pull request by maryamasaaditeh**

### CODE REVIEW

**Review by dustinburson — COMMENTED** [review]
Overrall looks good.  Please take this branch and test using the deployment steps here: https://github.com/microsoft/iomt-fhir/blob/main/docs/BicepInstallation.md

That will validate with the changes nothing is broken.  Thanks!

**Comment by maryamasaaditeh** [comment]
> Overrall looks good. Please take this branch and test using the deployment steps here: https://github.com/microsoft/iomt-fhir/blob/main/docs/BicepInstallation.md
> 
> That will validate with the changes nothing is broken. Thanks!

I have created the deployment using mentioned institutions: 
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/ab309d4e-4c2e-4241-be2e-08e1c8dd4246/resourceGroups/mariomt/providers/Microsoft.HealthcareApis/workspaces/mariomthw/fhirservices/mariomtfs/overview
all the resources created under this resource group : "mariomt"

**Review by dustinburson — APPROVED** [review]

**Comment by maryamasaaditeh** [comment]
> @maryamasaaditeh please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

**Comment by maryamasaaditeh** [comment]
Successful PR build Pipeline : https://microsofthealthoss.visualstudio.com/FhirServer/_build/results?buildId=42870&view=results

**Comment by maryamasaaditeh** [comment]
Closing the PR and will open another to get all the checks enabled.

**Pull request closed without merging**
